.PHONY: $(SL_SIMPLE_CLEAN) $(SL_SIMPLE_PURGE)

include $(wildcard $(SL_SIMPLE_OBJ_DIR)/*.d)

$(SL_SIMPLE_TARGET): $(P_SL_SIMPLE_OBJ) $(P_CMMN_OBJ)
	$(C) $(LD_FLAGS) $(LD_SHARED_FLAGS) $(SL_SIMPLE_LD_PFLAGS) $(P_SL_SIMPLE_OBJ) $(P_CMMN_OBJ) -o $@ $(SL_SIMPLE_LD_SFLAGS)

$(SL_SIMPLE_CLEAN):
	$(RM) $(RM_FLAGS) $(SL_SIMPLE_TARGET)
	$(RM) $(RM_FLAGS) $(P_SL_SIMPLE_OBJ) $(SL_SIMPLE_OBJ_DIR)/*.d

$(SL_SIMPLE_PURGE): $(SL_SIMPLE_CLEAN) $(CMMN_CLEAN) $(LM_CLEAN)
	$(RM) $(RM_FLAGS) $(SL_SIMPLE_TARGET)
	$(RM) $(RM_FLAGS) $(P_SL_SIMPLE_OBJ) $(SL_SIMPLE_OBJ_DIR)/*.d

$(SL_SIMPLE_OBJ_DIR)/%.o : $(SL_SIMPLE_DIR)/%.c $(SL_SIMPLE_DIR)/%.h
	$(C) $(CPP_FLAGS) $(CXX_SHARED_FLAGS) $(SL_SIMPLE_CPP_OPT) $(SL_SIMPLE_CPP_INC_FLAGS) $< -o $@

$(SL_SIMPLE_OBJ_DIR)/%.o : $(SL_SIMPLE_DIR)/%.c
	$(C) $(CPP_FLAGS) $(CXX_SHARED_FLAGS) $(SL_SIMPLE_CPP_OPT) $(SL_SIMPLE_CPP_INC_FLAGS) $< -o $@

include $(CMMN_DIR)/rules.mk

