#ifndef _ENV_NAME_H
#define _ENV_NAME_H

#define ENV_SCHED_ENABLE_TRACE_ALL "VIVM_SCHED_TRACE_ALL"
#define ENV_SCHED_ENABLE_TRACE     "VIVM_SCHED_TRACE"
#define ENV_SCHED_ENABLE_TRACE_ERR "VIVM_SCHED_TRACE_ERR"
#define ENV_SCHED_SHM_PATH         "VIVM_SCHED_SHM_PATH"
#define ENV_SCHED_RDMA_PORT        "VIVM_SCHED_RDMA_PORT"
#define ENV_SCHED_INET_PORT        "VIVM_SCHED_INET_PORT"

#define DEF_SCHED_RDMA_PORT        "51530"
#define DEF_SCHED_INET_PORT        "51531"

#define ENV_AGENT_ENABLE_TRACE_ALL "VIVM_AGENT_TRACE_ALL"
#define ENV_AGENT_ENABLE_TRACE     "VIVM_AGENT_TRACE"
#define ENV_AGENT_ENABLE_TRACE_ERR "VIVM_AGENT_TRACE_ERR"
#define ENV_AGENT_SHM_PATH         "VIVM_AGENT_SHM_PATH"
#define ENV_AGENT_RDMA_PORT        "VIVM_AGENT_RDMA_PORT"
#define ENV_AGENT_INET_PORT        "VIVM_AGENT_INET_PORT"

#define DEF_AGENT_RDMA_PORT        "51532"
#define DEF_AGENT_INET_PORT        "51533"

#define ENV_API_ENABLE_TRACE_ALL   "VIVM_API_TRACE_ALL"
#define ENV_API_ENABLE_TRACE       "VIVM_API_TRACE"
#define ENV_API_ENABLE_TRACE_ERR   "VIVM_API_TRACE_ERR"
//#define ENV_API_SHM_PATH           "VIVM_SHM_PATH"
//#define ENV_API_RDMA_PORT          "VIVM_RDMA_PORT"
//#define ENV_API_INET_PORT          "VIVM_INET_PORT"
#define ENV_API_IS_DESCENDANT      "VIVM_IS_DESCENDANT"

#define DEF_API_RDMA_PORT          "51534"
#define DEF_API_INET_PORT          "51535"


#endif //_ENV_NAME_H

