.PHONY: $(SCHEDLIB_CLEAN) $(SCHEDLIB_PURGE)

include $(wildcard $(SCHEDLIB_OBJ_DIR)/*.d)

$(SCHEDLIB_TARGET): $(CH_TARGET) $(P_SCHEDLIB_OBJ) $(P_CMMN_OBJ)
	$(CPP) $(LD_FLAGS) $(LD_SHARED_FLAGS) $(SCHEDLIB_LD_PFLAGS) $(P_SCHEDLIB_OBJ) $(P_CMMN_OBJ) -o $@ $(SCHEDLIB_LD_SFLAGS)

$(SCHEDLIB_CLEAN):
	$(RM) $(RM_FLAGS) $(SCHEDLIB_TARGET)
	$(RM) $(RM_FLAGS) $(P_SCHEDLIB_OBJ) $(SCHEDLIB_OBJ_DIR)/*.d

$(SCHEDLIB_PURGE): $(SCHEDLIB_CLEAN) $(CMMN_CLEAN) $(CH_CLEAN) $(LM_CLEAN)
	$(RM) $(RM_FLAGS) $(SCHEDLIB_TARGET)
	$(RM) $(RM_FLAGS) $(P_SCHEDLIB_OBJ) $(SCHEDLIB_OBJ_DIR)/*.d

$(SCHEDLIB_OBJ_DIR)/%.o : $(SCHEDLIB_DIR)/%.cpp $(SCHEDLIB_DIR)/%.h
	$(CPP) $(CPP_FLAGS) $(CXX_SHARED_FLAGS) $(SCHEDLIB_CPP_OPT) $(SCHEDLIB_CPP_INC_FLAGS) $< -o $@

$(SCHEDLIB_OBJ_DIR)/%.o : $(SCHEDLIB_DIR)/%.cpp
	$(CPP) $(CPP_FLAGS) $(CXX_SHARED_FLAGS) $(SCHEDLIB_CPP_OPT) $(SCHEDLIB_CPP_INC_FLAGS) $< -o $@

include $(CH_DIR)/rules.mk
include $(CMMN_DIR)/rules.mk

