
.PHONY: all clean

all:
	$(MAKE) -C compreg
	$(MAKE) -C peskill
	$(MAKE) -C memalloc
	$(MAKE) -C nstcomp
	$(MAKE) -C dnstcomp
	$(MAKE) -C recursion

clean:
	$(MAKE) -C compreg clean
	$(MAKE) -C peskill clean
	$(MAKE) -C memalloc clean
	$(MAKE) -C nstcomp clean
	$(MAKE) -C dnstcomp clean
	$(MAKE) -C recursion clean

